//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“ArticleEntities.cs”的分部类“public partial class ArticleEntities”}添加属性
// </auto-generated>
//
//  <copyright file="ArticleEntities.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;

using KaPai.Pay.Identity.Entities;
using System.Text.Json;

namespace KaPai.Pay.Provide.Entities
{
    /// <summary>
    /// 实体类：收款号列表信息
    /// </summary>
    [Description("收款号列表信息")]
    public partial class ArticleEntities : EntityBase<Guid>, ISoftDeletable, ICreationAudited<int>, IUpdateAudited<int>
    {
        /// <summary>
        /// 获取或设置 名称
        /// </summary>
        [DisplayName("名称"), StringLength(30)]
        public string Name { get; set; }

        /// <summary>
        /// 获取或设置 附加参数
        /// </summary>
        [DisplayName("附加参数")]
        public JsonDocument Extra { get; set; }

        /// <summary>
        /// 获取或设置 账号备注
        /// </summary>
        [DisplayName("账号备注"), StringLength(200)]
        public string Remarks { get; set; }

        /// <summary>
        /// 获取或设置 状态
        /// </summary>
        [DisplayName("状态")]
        public int Status { get; set; }

        /// <summary>
        /// 获取或设置 删除时间
        /// </summary>
        [DisplayName("删除时间")]
        public DateTime? DeletedTime { get; set; }

        /// <summary>
        /// 获取或设置 创建者
        /// </summary>
        [DisplayName("创建者")]
        public int? CreatorId { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 更新者
        /// </summary>
        [DisplayName("更新者")]
        public int? LastUpdaterId { get; set; }

        /// <summary>
        /// 获取或设置 更新时间
        /// </summary>
        [DisplayName("更新时间")]
        public DateTime? LastUpdatedTime { get; set; }

        /// <summary>
        /// 获取或设置 用户ID
        /// </summary>
        [DisplayName("用户ID"), UserFlag]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 类别ID
        /// </summary>
        [DisplayName("类别ID")]
        public Guid ArticleAssortId { get; set; }

        /// <summary>
        /// 获取或设置 类别
        /// </summary>
        [DisplayName("类别")]
        public virtual ArticleAssort ArticleAssort { get; set; }

        /// <summary>
        /// 获取或设置 所属用户
        /// </summary>
        [DisplayName("所属用户")]
        public virtual User User { get; set; }

    }
}

