//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“ArticleAssort.cs”的分部类“public partial class ArticleAssort”}添加属性
// </auto-generated>
//
//  <copyright file="ArticleAssort.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;

using KaPai.Pay.Channel.Entities;

namespace KaPai.Pay.Provide.Entities
{
    /// <summary>
    /// 实体类：收款分类列表信息
    /// </summary>
    [Description("收款分类列表信息")]
    public partial class ArticleAssort : EntityBase<Guid>, ICreatedTime
    {
        /// <summary>
        /// 获取或设置 分类名称
        /// </summary>
        [DisplayName("分类名称"), Required, StringLength(50)]
        public string Name { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 通道ID
        /// </summary>
        [DisplayName("通道ID")]
        public Guid ChannelId { get; set; }

        /// <summary>
        /// 获取或设置 通道
        /// </summary>
        [DisplayName("通道")]
        public virtual Channels Channel { get; set; }

    }
}

