//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“Points.cs”的分部类“public partial class Points”}添加属性
// </auto-generated>
//
//  <copyright file="Points.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;

using KaPai.Pay.Identity.Entities;

namespace KaPai.Pay.Provide.Entities
{
    /// <summary>
    /// 实体类：供应商实时积分信息
    /// </summary>
    [Description("供应商实时积分信息")]
    public partial class Points : EntityBase<Guid>, ICreatedTime
    {
        /// <summary>
        /// 获取或设置 积分
        /// </summary>
        [DisplayName("积分")]
        public long Point { get; set; }


        /// <summary>
        /// 获取或设置 冻结余额
        /// </summary>
        [DisplayName("冻结积分")]
        public long FreezePoint { get; set; }

        /// <summary>
        /// 获取或设置 累计积分
        /// </summary>
        [DisplayName("累计积分")]
        public long Accumulative { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 用户Id
        /// </summary>
        [DisplayName("用户Id"), UserFlag]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 用户
        /// </summary>
        [DisplayName("用户")]
        public virtual User User { get; set; }

    }
}

