//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“ProvideExtra.cs”的分部类“public partial class ProvideExtra”}添加属性
// </auto-generated>
//
//  <copyright file="ProvideExtra.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;

using KaPai.Pay.Identity.Entities;
using System.Text.Json;

namespace KaPai.Pay.Provide.Entities
{
    /// <summary>
    /// 实体类：供应商参数信息
    /// </summary>
    [Description("供应商参数信息")]
    public partial class ProvideExtra : EntityBase<Guid>, ICreatedTime
    {
        /// <summary>
        /// 获取或设置 附加参数
        /// </summary>
        [DisplayName("附加参数")]
        public JsonDocument Extra { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 用户ID
        /// </summary>
        [DisplayName("用户ID"), UserFlag]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 上级用户ID
        /// </summary>
        [DisplayName("上级用户ID")]
        public int? PUserId { get; set; }

        /// <summary>
        /// 获取或设置 用户
        /// </summary>
        [DisplayName("用户")]
        public virtual User User { get; set; }

        /// <summary>
        /// 获取或设置 上级用户
        /// </summary>
        [DisplayName("上级用户")]
        public virtual User ParentUser { get; set; }

    }
}

