// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前实体 Amounts 添加方法，可新建文件“MerchantServiceBase.Amounts.cs”的分部类“public abstract partial class MerchantServiceBase”添加功能
//      2.纵向扩展：如需要重写当前实体 Amounts 的业务实现，可新建文件“MerchantService.Amounts.cs”的分部类“public partial class MerchantService”对现有方法进行方法重写实现
// </auto-generated>
//
//  <copyright file="MerchantServiceBase.Amounts.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Dependency;
using OSharp.Extensions;
using OSharp.Mapping;

using KaPai.Pay.Merchant.Dtos;
using KaPai.Pay.Merchant.Entities;


namespace KaPai.Pay.Merchant
{
    public abstract partial class MerchantServiceBase
    {
        /// <summary>
        /// 获取 商户实时余额信息查询数据集
        /// </summary>
        public IQueryable<Amounts> Amountses
        {
            get { return AmountsRepository.QueryAsNoTracking(); }
        }

        /// <summary>
        /// 检查商户实时余额信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的商户实时余额信息编号</param>
        /// <returns>商户实时余额信息是否存在</returns>
        public virtual Task<bool> CheckAmountsExists(Expression<Func<Amounts, bool>> predicate, Guid id = default(Guid))
        {
            return AmountsRepository.CheckExistsAsync(predicate, id);
        }
        
        /// <summary>
        /// 更新商户实时余额信息
        /// </summary>
        /// <param name="dtos">包含更新信息的商户实时余额信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> UpdateAmountses(params AmountsInputDto[] dtos)
        {
            Check.Validate<AmountsInputDto, Guid>(dtos, nameof(dtos));
            return AmountsRepository.UpdateAsync(dtos);
        }
    }
}
