// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，请在控制器类型 MerchantService 进行继承重写
// </auto-generated>
//
//  <copyright file="IMerchantServiceBase.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Threading.Tasks;

using OSharp.Core.Systems;
using OSharp.Data;
using OSharp.Entity;
using OSharp.EventBuses;
using OSharp.Extensions;
using OSharp.Identity;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

using KaPai.Pay.Merchant.Dtos;
using KaPai.Pay.Merchant.Entities;


namespace KaPai.Pay.Merchant
{
    /// <summary>
    /// 业务实现基类：商户模块
    /// </summary>
    public abstract partial class MerchantServiceBase : IMerchantContract
    {
        /// <summary>
        /// 初始化一个<see cref="MerchantService"/>类型的新实例
        /// </summary>
        protected MerchantServiceBase(IServiceProvider provider)
        {
            ServiceProvider = provider;
            Logger = provider.GetLogger(GetType());
        }
    
        #region 属性

        /// <summary>
        /// 获取或设置 服务提供者对象
        /// </summary>
        protected IServiceProvider ServiceProvider { get; }

        /// <summary>
        /// 获取或设置 日志对象
        /// </summary>
        protected ILogger Logger { get; }

        /// <summary>
        /// 获取或设置 商户订单列表信息仓储对象
        /// </summary>
        protected IRepository<Orders, Guid> OrdersRepository => ServiceProvider.GetService<IRepository<Orders, Guid>>();
        
        /// <summary>
        /// 获取或设置 商户实时余额信息仓储对象
        /// </summary>
        protected IRepository<Amounts, Guid> AmountsRepository => ServiceProvider.GetService<IRepository<Amounts, Guid>>();
        
        /// <summary>
        /// 获取或设置 余额变动记录信息仓储对象
        /// </summary>
        protected IRepository<AmountsLog, Guid> AmountsLogRepository => ServiceProvider.GetService<IRepository<AmountsLog, Guid>>();
        
        /// <summary>
        /// 获取或设置 商户参数信息仓储对象
        /// </summary>
        protected IRepository<MerchantExtra, Guid> MerchantExtraRepository => ServiceProvider.GetService<IRepository<MerchantExtra, Guid>>();
        
        /// <summary>
        /// 获取或设置 订单回调记录信息仓储对象
        /// </summary>
        protected IRepository<OrderBackLog, Guid> OrderBackLogRepository => ServiceProvider.GetService<IRepository<OrderBackLog, Guid>>();
        
        /// <summary>
        /// 获取 事件总线
        /// </summary>
        protected IEventBus EventBus => ServiceProvider.GetService<IEventBus>();

        /// <summary>
        /// 获取 设置存储对象
        /// </summary>
        protected IKeyValueStore KeyValueStore => ServiceProvider.GetService<IKeyValueStore>();

        #endregion
    }
}
