//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的映射，可新建文件“ChannelTypeConfiguration.cs”的分部类“public partial class ChannelTypeConfiguration”}实现分部方法 EntityConfigurationAppend 进行扩展
// </auto-generated>
//
//  <copyright file="ChannelTypeConfiguration.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using OSharp.Entity;

using KaPai.Pay.Channel.Entities;


namespace KaPai.Pay.EntityConfiguration.Channel
{
    /// <summary>
    /// 实体配置类：通道供应商账号类型信息
    /// </summary>
    public partial class ChannelTypeConfiguration : EntityTypeConfigurationBase<ChannelType, Guid>
    {
        /// <summary>
        /// 重写以实现实体类型各个属性的数据库配置
        /// </summary>
        /// <param name="builder">实体类型创建器</param>
        public override void Configure(EntityTypeBuilder<ChannelType> builder)
        {
            builder.HasOne<Channels>(m => m.Channel).WithOne().HasForeignKey<ChannelType>(m => m.ChannelId).OnDelete(DeleteBehavior.SetNull);

            EntityConfigurationAppend(builder);
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void EntityConfigurationAppend(EntityTypeBuilder<ChannelType> builder);
    }
}

