// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1. 横向扩展：如需给当前模块添加方法接口，可新建文件“IProvideContract.cs”的分部接口“public partial interface IProvideContract”添加方法，并添加相应新的分部基类 abstract partial class ProvideServiceBase 实现新方法
// </auto-generated>
//
//  <copyright file="IProvideContract.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Extensions;

using KaPai.Pay.Provide.Dtos;
using KaPai.Pay.Provide.Entities;


namespace KaPai.Pay.Provide
{
    /// <summary>
    /// 业务契约接口：供应商模块
    /// </summary>
    public partial interface IProvideContract
    {
        #region 收款分类列表信息业务

        /// <summary>
        /// 获取 收款分类列表信息查询数据集
        /// </summary>
        IQueryable<ArticleAssort> ArticleAssorts { get; }

        /// <summary>
        /// 检查收款分类列表信息信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的收款分类列表信息编号</param>
        /// <returns>收款分类列表信息是否存在</returns>
        Task<bool> CheckArticleAssortExists(Expression<Func<ArticleAssort, bool>> predicate, Guid id = default(Guid));
        
        /// <summary>
        /// 添加收款分类列表信息信息
        /// </summary>
        /// <param name="dtos">要添加的收款分类列表信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> CreateArticleAssorts(params ArticleAssortInputDto[] dtos);
            
        /// <summary>
        /// 更新收款分类列表信息信息
        /// </summary>
        /// <param name="dtos">包含更新信息的收款分类列表信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> UpdateArticleAssorts(params ArticleAssortInputDto[] dtos);
            
        /// <summary>
        /// 删除收款分类列表信息信息
        /// </summary>
        /// <param name="ids">要删除的收款分类列表信息编号</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> DeleteArticleAssorts(params Guid[] ids);
        

        #endregion
        
        #region 收款号列表信息业务

        /// <summary>
        /// 获取 收款号列表信息查询数据集
        /// </summary>
        IQueryable<ArticleEntities> ArticleEntitieses { get; }

        /// <summary>
        /// 检查收款号列表信息信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的收款号列表信息编号</param>
        /// <returns>收款号列表信息是否存在</returns>
        Task<bool> CheckArticleEntitiesExists(Expression<Func<ArticleEntities, bool>> predicate, Guid id = default(Guid));
        
        /// <summary>
        /// 添加收款号列表信息信息
        /// </summary>
        /// <param name="dtos">要添加的收款号列表信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> CreateArticleEntitieses(ArticleEntitiesInputDto[] dtos);

        /// <summary>
        /// 更新收款号列表信息信息
        /// </summary>
        /// <param name="dtos">包含更新信息的收款号列表信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> UpdateArticleEntitieses(params ArticleEntitiesInputDto[] dtos);
    
        #endregion
        
        #region 供应商实时积分信息业务

        /// <summary>
        /// 获取 供应商实时积分信息查询数据集
        /// </summary>
        IQueryable<Points> Pointses { get; }

        /// <summary>
        /// 检查供应商实时积分信息信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的供应商实时积分信息编号</param>
        /// <returns>供应商实时积分信息是否存在</returns>
        Task<bool> CheckPointsExists(Expression<Func<Points, bool>> predicate, Guid id = default(Guid));
        
        #endregion
        
        #region 积分变动记录信息业务

        /// <summary>
        /// 获取 积分变动记录信息查询数据集
        /// </summary>
        IQueryable<PointsLog> PointsLogs { get; }

        /// <summary>
        /// 检查积分变动记录信息信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的积分变动记录信息编号</param>
        /// <returns>积分变动记录信息是否存在</returns>
        Task<bool> CheckPointsLogExists(Expression<Func<PointsLog, bool>> predicate, Guid id = default(Guid));
        
        #endregion
        
        #region 供应商参数信息业务

        /// <summary>
        /// 获取 供应商参数信息查询数据集
        /// </summary>
        IQueryable<ProvideExtra> ProvideExtras { get; }

        /// <summary>
        /// 检查供应商参数信息信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的供应商参数信息编号</param>
        /// <returns>供应商参数信息是否存在</returns>
        Task<bool> CheckProvideExtraExists(Expression<Func<ProvideExtra, bool>> predicate, Guid id = default(Guid));
            
        /// <summary>
        /// 更新供应商参数信息信息
        /// </summary>
        /// <param name="dtos">包含更新信息的供应商参数信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> UpdateProvideExtras(params ProvideExtraInputDto[] dtos);
    
        #endregion
        
    }
}
