// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前实体 PointsLog 添加方法，可新建文件“ProvideServiceBase.PointsLog.cs”的分部类“public abstract partial class ProvideServiceBase”添加功能
//      2.纵向扩展：如需要重写当前实体 PointsLog 的业务实现，可新建文件“ProvideService.PointsLog.cs”的分部类“public partial class ProvideService”对现有方法进行方法重写实现
// </auto-generated>
//
//  <copyright file="ProvideServiceBase.PointsLog.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Dependency;
using OSharp.Extensions;
using OSharp.Mapping;

using KaPai.Pay.Provide.Dtos;
using KaPai.Pay.Provide.Entities;


namespace KaPai.Pay.Provide
{
    public abstract partial class ProvideServiceBase
    {
        /// <summary>
        /// 获取 积分变动记录信息查询数据集
        /// </summary>
        public IQueryable<PointsLog> PointsLogs
        {
            get { return PointsLogRepository.QueryAsNoTracking(); }
        }

        /// <summary>
        /// 检查积分变动记录信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的积分变动记录信息编号</param>
        /// <returns>积分变动记录信息是否存在</returns>
        public virtual Task<bool> CheckPointsLogExists(Expression<Func<PointsLog, bool>> predicate, Guid id = default(Guid))
        {
            return PointsLogRepository.CheckExistsAsync(predicate, id);
        }
    }
}
