// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，请在控制器类型 ProvideService 进行继承重写
// </auto-generated>
//
//  <copyright file="IProvideServiceBase.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Threading.Tasks;

using OSharp.Core.Systems;
using OSharp.Data;
using OSharp.Entity;
using OSharp.EventBuses;
using OSharp.Extensions;
using OSharp.Identity;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

using KaPai.Pay.Provide.Dtos;
using KaPai.Pay.Provide.Entities;


namespace KaPai.Pay.Provide
{
    /// <summary>
    /// 业务实现基类：供应商模块
    /// </summary>
    public abstract partial class ProvideServiceBase : IProvideContract
    {
        /// <summary>
        /// 初始化一个<see cref="ProvideService"/>类型的新实例
        /// </summary>
        protected ProvideServiceBase(IServiceProvider provider)
        {
            ServiceProvider = provider;
            Logger = provider.GetLogger(GetType());
        }
    
        #region 属性

        /// <summary>
        /// 获取或设置 服务提供者对象
        /// </summary>
        protected IServiceProvider ServiceProvider { get; }

        /// <summary>
        /// 获取或设置 日志对象
        /// </summary>
        protected ILogger Logger { get; }

        /// <summary>
        /// 获取或设置 收款分类列表信息仓储对象
        /// </summary>
        protected IRepository<ArticleAssort, Guid> ArticleAssortRepository => ServiceProvider.GetService<IRepository<ArticleAssort, Guid>>();
        
        /// <summary>
        /// 获取或设置 收款号列表信息仓储对象
        /// </summary>
        protected IRepository<ArticleEntities, Guid> ArticleEntitiesRepository => ServiceProvider.GetService<IRepository<ArticleEntities, Guid>>();
        
        /// <summary>
        /// 获取或设置 供应商实时积分信息仓储对象
        /// </summary>
        protected IRepository<Points, Guid> PointsRepository => ServiceProvider.GetService<IRepository<Points, Guid>>();
        
        /// <summary>
        /// 获取或设置 积分变动记录信息仓储对象
        /// </summary>
        protected IRepository<PointsLog, Guid> PointsLogRepository => ServiceProvider.GetService<IRepository<PointsLog, Guid>>();
        
        /// <summary>
        /// 获取或设置 供应商参数信息仓储对象
        /// </summary>
        protected IRepository<ProvideExtra, Guid> ProvideExtraRepository => ServiceProvider.GetService<IRepository<ProvideExtra, Guid>>();
        
        /// <summary>
        /// 获取 事件总线
        /// </summary>
        protected IEventBus EventBus => ServiceProvider.GetService<IEventBus>();

        /// <summary>
        /// 获取 设置存储对象
        /// </summary>
        protected IKeyValueStore KeyValueStore => ServiceProvider.GetService<IKeyValueStore>();

        #endregion
    }
}
