// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“OrderBackLogOutputDto.cs”的分部类“public partial class OrderBackLogOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="OrderBackLogOutputDto.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using KaPai.Pay.Merchant.Entities;

namespace KaPai.Pay.Merchant.Dtos
{
    /// <summary>
    /// 输入DTO：订单回调记录信息
    /// </summary>
    [MapFrom(typeof(OrderBackLog))]
    [Description("订单回调记录信息")]
    public partial class OrderBackLogOutputDto : IOutputDto, IDataAuthEnabled
    {
        /// <summary>
        /// 初始化一个<see cref="OrderBackLogOutputDto"/>类型的新实例
        /// </summary>
        public OrderBackLogOutputDto()
        { }

        /// <summary>
        /// 初始化一个<see cref="OrderBackLogOutputDto"/>类型的新实例
        /// </summary>
        public OrderBackLogOutputDto(OrderBackLog entity)
        {
            Id = entity.Id;
            CreatedTime = entity.CreatedTime;
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public Guid Id { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 是否可更新的数据权限状态
        /// </summary>
        public bool Updatable { get; set; }

        /// <summary>
        /// 获取或设置 是否可删除的数据权限状态
        /// </summary>
        public bool Deletable { get; set; }

    }
}
