// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“OrdersOutputDto.cs”的分部类“public partial class OrdersOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="OrdersOutputDto.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using OSharp.Entity;
using OSharp.Mapping;

using KaPai.Pay.Merchant.Entities;
using KaPai.Pay.Identity.Dtos;
using KaPai.Pay.Channel.Dtos;
using KaPai.Pay.Provide.Dtos;

namespace KaPai.Pay.Merchant.Dtos
{
    /// <summary>
    /// 输入DTO：商户订单列表信息
    /// </summary>
    [MapFrom(typeof(Orders))]
    [Description("商户订单列表信息")]
    public partial class OrdersOutputDto : IOutputDto, IDataAuthEnabled
    {
        /// <summary>
        /// 初始化一个<see cref="OrdersOutputDto"/>类型的新实例
        /// </summary>
        public OrdersOutputDto()
        { }

        /// <summary>
        /// 初始化一个<see cref="OrdersOutputDto"/>类型的新实例
        /// </summary>
        public OrdersOutputDto(Orders entity)
        {
            Id = entity.Id;
            UserId = entity.UserId;
            ChannelId = entity.ChannelId;
            ArticleAssortId = entity.ArticleAssortId;
            Orderid = entity.Orderid;
            CreatedAmount = entity.CreatedAmount;
            PayAmount = entity.PayAmount;
            Remark = entity.Remark;
            ClientId = entity.ClientId;
            ClientIp = entity.ClientIp;
            AsynUrl = entity.AsynUrl;
            JobId = entity.JobId;
            Status = entity.Status;
            CreatedTime = entity.CreatedTime;
            LastUpdaterId = entity.LastUpdaterId;
            LastUpdatedTime = entity.LastUpdatedTime;
            Channel_Name = entity.Channel.Name;
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public Guid Id { get; set; }

        /// <summary>
        /// 获取或设置 用户ID
        /// </summary>
        [DisplayName("用户ID")]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 通道ID
        /// </summary>
        [DisplayName("通道ID")]
        public Guid ChannelId { get; set; }

        /// <summary>
        /// 获取或设置 收款ID
        /// </summary>
        [DisplayName("收款ID")]
        public Guid? ArticleAssortId { get; set; }

        /// <summary>
        /// 获取或设置 订单号
        /// </summary>
        [DisplayName("订单号")]
        public string Orderid { get; set; }

        /// <summary>
        /// 获取或设置 创建金额
        /// </summary>
        [DisplayName("创建金额")]
        public long CreatedAmount { get; set; }

        /// <summary>
        /// 获取或设置 支付金额
        /// </summary>
        [DisplayName("支付金额")]
        public long PayAmount { get; set; }

        /// <summary>
        /// 获取或设置 订单备注
        /// </summary>
        [DisplayName("订单备注")]
        public string Remark { get; set; }

        /// <summary>
        /// 获取或设置 客户唯一码
        /// </summary>
        [DisplayName("客户唯一码")]
        public string ClientId { get; set; }

        /// <summary>
        /// 获取或设置 客户ip
        /// </summary>
        [DisplayName("客户ip")]
        public string ClientIp { get; set; }

        /// <summary>
        /// 获取或设置 回调地址
        /// </summary>
        [DisplayName("回调地址")]
        public string AsynUrl { get; set; }

        /// <summary>
        /// 获取或设置 异步任务id
        /// </summary>
        [DisplayName("异步任务id")]
        public string JobId { get; set; }

        /// <summary>
        /// 获取或设置 订单当前状态
        /// </summary>
        [DisplayName("订单当前状态")]
        public int Status { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 更新者
        /// </summary>
        [DisplayName("更新者")]
        public int? LastUpdaterId { get; set; }

        /// <summary>
        /// 获取或设置 更新时间
        /// </summary>
        [DisplayName("更新时间")]
        public DateTime? LastUpdatedTime { get; set; }

        /// <summary>
        /// 获取或设置 是否可更新的数据权限状态
        /// </summary>
        public bool Updatable { get; set; }

        /// <summary>
        /// 获取或设置 是否可删除的数据权限状态
        /// </summary>
        public bool Deletable { get; set; }

    }
}
