// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“OrdersOutputDto.cs”的分部类“public partial class OrdersOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="OrdersOutputDto.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.ComponentModel;

using OSharp.Entity;
using OSharp.Mapping;

using KaPai.Pay.Merchant.Entities;

namespace KaPai.Pay.Merchant.Dtos
{
    /// <summary>
    /// 输入DTO：商户订单列表信息
    /// </summary>
    [Description("商户回调信息")]
    public class OrdersOutBack : IOutputDto
    {
        /// <summary>
        /// 初始化一个<see cref="OrdersOutputDto"/>类型的新实例
        /// </summary>
        public OrdersOutBack()
        { }

        /// <summary>
        /// 初始化一个<see cref="OrdersOutputDto"/>类型的新实例
        /// </summary>
        public OrdersOutBack(Orders entity)
        {
            Id = entity.Id;
            UserId = entity.UserId;
            ChannelId = entity.ChannelId;
            Orderid = entity.Orderid;
            CreatedAmount = entity.CreatedAmount;
            PayAmount = entity.PayAmount;
            Remark = entity.Remark;
            ClientId = entity.ClientId;
            ClientIp = entity.ClientIp;
            Status = entity.Status;
            Time = Convert.ToInt64((DateTime.UtcNow - new DateTime(1970, 1, 1, 0, 0, 0, 0)).TotalSeconds);
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public Guid Id { get; set; }

        /// <summary>
        /// 获取或设置 用户ID
        /// </summary>
        [DisplayName("用户ID")]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 通道ID
        /// </summary>
        [DisplayName("通道ID")]
        public Guid ChannelId { get; set; }

        /// <summary>
        /// 获取或设置 订单号
        /// </summary>
        [DisplayName("订单号")]
        public string Orderid { get; set; }

        /// <summary>
        /// 获取或设置 创建金额
        /// </summary>
        [DisplayName("创建金额")]
        public long CreatedAmount { get; set; }

        /// <summary>
        /// 获取或设置 支付金额
        /// </summary>
        [DisplayName("支付金额")]
        public long PayAmount { get; set; }

        /// <summary>
        /// 获取或设置 订单备注
        /// </summary>
        [DisplayName("订单备注")]
        public string Remark { get; set; }

        /// <summary>
        /// 获取或设置 客户唯一码
        /// </summary>
        [DisplayName("客户唯一码")]
        public string ClientId { get; set; }

        /// <summary>
        /// 获取或设置 客户ip
        /// </summary>
        [DisplayName("客户ip")]
        public string ClientIp { get; set; }


        /// <summary>
        /// 获取或设置 订单当前状态
        /// </summary>
        [DisplayName("订单当前状态")]
        public int Status { get; set; }


        [DisplayName("签名")]
        public string Sign { get; set; }

        /// <summary>
        /// 时间
        /// </summary>
        [DisplayName("时间")]
        public long Time { get; set;}


         
    }
}
