//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“OrderBackLog.cs”的分部类“public partial class OrderBackLog”}添加属性
// </auto-generated>
//
//  <copyright file="OrderBackLog.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;


namespace KaPai.Pay.Merchant.Entities
{
    /// <summary>
    /// 实体类：订单回调记录信息
    /// </summary>
    [Description("订单回调记录信息")]
    public partial class OrderBackLog : EntityBase<Guid>, ICreatedTime
    {
        /// <summary>
        /// 获取或设置 返回信息
        /// </summary>
        [DisplayName("返回信息"), StringLength(500)]
        public string Message { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 订单ID
        /// </summary>
        [DisplayName("订单ID")]
        public Guid OrderId { get; set; }

        /// <summary>
        /// 获取或设置 订单信息
        /// </summary>
        [DisplayName("订单信息")]
        public virtual Orders Order { get; set; }

    }
}

