//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“Orders.cs”的分部类“public partial class Orders”}添加属性
// </auto-generated>
//
//  <copyright file="Orders.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;

using KaPai.Pay.Identity.Entities;
using KaPai.Pay.Channel.Entities;
using KaPai.Pay.Provide.Entities;

namespace KaPai.Pay.Merchant.Entities
{
    /// <summary>
    /// 实体类：商户订单列表信息
    /// </summary>
    [Description("商户订单列表信息")]
    public partial class Orders : EntityBase<Guid>, ICreatedTime, IUpdateAudited<int>
    {
        /// <summary>
        /// 获取或设置 订单号
        /// </summary>
        [DisplayName("订单号"), Required, StringLength(100)]
        public string Orderid { get; set; }

        /// <summary>
        /// 获取或设置 创建金额
        /// </summary>
        [DisplayName("创建金额")]
        public long CreatedAmount { get; set; }

        /// <summary>
        /// 获取或设置 支付金额
        /// </summary>
        [DisplayName("支付金额")]
        public long PayAmount { get; set; }

        /// <summary>
        /// 获取或设置 订单备注
        /// </summary>
        [DisplayName("订单备注"), StringLength(100)]
        public string Remark { get; set; }

        /// <summary>
        /// 获取或设置 客户唯一码
        /// </summary>
        [DisplayName("客户唯一码"), StringLength(50)]
        public string ClientId { get; set; }

        /// <summary>
        /// 获取或设置 客户ip
        /// </summary>
        [DisplayName("客户ip"), StringLength(50)]
        public string ClientIp { get; set; }

        /// <summary>
        /// 获取或设置 回调地址
        /// </summary>
        [DisplayName("回调地址"), Required, StringLength(200)]
        public string AsynUrl { get; set; }

        /// <summary>
        /// 获取或设置 异步任务id
        /// </summary>
        [DisplayName("异步任务id"), StringLength(50)]
        public string JobId { get; set; }

        /// <summary>
        /// 获取或设置 订单当前状态
        /// </summary>
        [DisplayName("订单当前状态")]
        public int Status { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 更新者
        /// </summary>
        [DisplayName("更新者")]
        public int? LastUpdaterId { get; set; }

        /// <summary>
        /// 获取或设置 更新时间
        /// </summary>
        [DisplayName("更新时间")]
        public DateTime? LastUpdatedTime { get; set; }

        /// <summary>
        /// 获取或设置 用户ID
        /// </summary>
        [DisplayName("用户ID"), UserFlag]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 通道ID
        /// </summary>
        [DisplayName("通道ID")]
        public Guid ChannelId { get; set; }

        /// <summary>
        /// 获取或设置 收款ID
        /// </summary>
        [DisplayName("收款ID")]
        public Guid? ArticleAssortId { get; set; }

        /// <summary>
        /// 获取或设置 回调状态
        /// </summary>
        [DisplayName("回调状态")]
        public int CallBack { get; set; }

        /// <summary>
        /// 获取或设置 收款实体
        /// </summary>
        [DisplayName("收款实体")]
        public virtual ArticleEntities ArticleAssort { get; set; }

        /// <summary>
        /// 获取或设置 订单通道
        /// </summary>
        [DisplayName("订单通道")]
        public virtual Channels Channel { get; set; }

        /// <summary>
        /// 获取或设置 用户
        /// </summary>
        [DisplayName("用户")]
        public virtual User User { get; set; }

        /// <summary>
        /// 获取或设置 回调日志
        /// </summary>
        [DisplayName("回调日志")]
        public virtual ICollection<OrderBackLog> BackLog { get; set; }



    }
}

