// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“ArticleEntitiesOutputDto.cs”的分部类“public partial class ArticleEntitiesOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="ArticleEntitiesOutputDto.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using KaPai.Pay.Provide.Entities;
using KaPai.Pay.Identity.Dtos;
using System.Text.Json;
using AutoMapper.Configuration.Annotations;
using KaPai.Pay.My;

namespace KaPai.Pay.Provide.Dtos
{
    /// <summary>
    /// 输入DTO：收款号列表信息
    /// </summary>
    [MapFrom(typeof(ArticleEntities))]
    [Description("收款号列表信息")]
    public partial class ArticleEntitiesOutputDto : IOutputDto, IDataAuthEnabled
    {
        /// <summary>
        /// 初始化一个<see cref="ArticleEntitiesOutputDto"/>类型的新实例
        /// </summary>
        public ArticleEntitiesOutputDto()
        { }

        /// <summary>
        /// 初始化一个<see cref="ArticleEntitiesOutputDto"/>类型的新实例
        /// </summary>
        public ArticleEntitiesOutputDto(ArticleEntities entity)
        {
            Id = entity.Id;
            UserId = entity.UserId;
            ArticleAssortId = entity.ArticleAssortId;
            Name = entity.Name;
            Remarks = entity.Remarks;
            Status = entity.Status;
            CreatorId = entity.CreatorId;
            CreatedTime = entity.CreatedTime;
            LastUpdaterId = entity.LastUpdaterId;
            LastUpdatedTime = entity.LastUpdatedTime;
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public Guid Id { get; set; }

        /// <summary>
        /// 获取或设置 用户ID
        /// </summary>
        [DisplayName("用户ID")]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 类别ID
        /// </summary>
        [DisplayName("类别ID")]
        public Guid ArticleAssortId { get; set; }

        /// <summary>
        /// 获取或设置 名称
        /// </summary>
        [DisplayName("名称")]
        public string Name { get; set; }


        [DisplayName("附加参数")]
        public IDictionary<string, object> Extra { get; set; }

        /// <summary>
        /// 获取或设置 账号备注
        /// </summary>
        [DisplayName("账号备注")]
        public string Remarks { get; set; }

        /// <summary>
        /// 获取或设置 状态
        /// </summary>
        [DisplayName("状态")]
        public int Status { get; set; }

        /// <summary>
        /// 获取或设置 创建者
        /// </summary>
        [DisplayName("创建者")]
        public int? CreatorId { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 更新者
        /// </summary>
        [DisplayName("更新者")]
        public int? LastUpdaterId { get; set; }

        /// <summary>
        /// 获取或设置 更新时间
        /// </summary>
        [DisplayName("更新时间")]
        public DateTime? LastUpdatedTime { get; set; }

        /// <summary>
        /// 获取或设置 是否可更新的数据权限状态
        /// </summary>
        public bool Updatable { get; set; }

        /// <summary>
        /// 获取或设置 是否可删除的数据权限状态
        /// </summary>
        public bool Deletable { get; set; }

    }
}
