// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“ArticleAssortOutputDto.cs”的分部类“public partial class ArticleAssortOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="ArticleAssortOutputDto.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using KaPai.Pay.Provide.Entities;
using KaPai.Pay.Channel.Dtos;

namespace KaPai.Pay.Provide.Dtos
{
    /// <summary>
    /// 输入DTO：收款分类列表信息
    /// </summary>
    [MapFrom(typeof(ArticleAssort))]
    [Description("收款分类列表信息")]
    public partial class ArticleAssortOutputDto : IOutputDto, IDataAuthEnabled
    {
        /// <summary>
        /// 初始化一个<see cref="ArticleAssortOutputDto"/>类型的新实例
        /// </summary>
        public ArticleAssortOutputDto()
        { }

        /// <summary>
        /// 初始化一个<see cref="ArticleAssortOutputDto"/>类型的新实例
        /// </summary>
        public ArticleAssortOutputDto(ArticleAssort entity)
        {
            Id = entity.Id;
            Name = entity.Name;
            ChannelId = entity.ChannelId;
            CreatedTime = entity.CreatedTime;
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public Guid Id { get; set; }

        /// <summary>
        /// 获取或设置 分类名称
        /// </summary>
        [DisplayName("分类名称")]
        public string Name { get; set; }

        /// <summary>
        /// 获取或设置 通道ID
        /// </summary>
        [DisplayName("通道ID")]
        public Guid ChannelId { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 是否可更新的数据权限状态
        /// </summary>
        public bool Updatable { get; set; }

        /// <summary>
        /// 获取或设置 是否可删除的数据权限状态
        /// </summary>
        public bool Deletable { get; set; }

    }
}
