// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“ArticleEntitiesInputDto.cs”的分部类“public partial class ArticleEntitiesInputDto”}添加属性
// </auto-generated>
//
//  <copyright file="ArticleEntitiesInputDto.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using KaPai.Pay.Provide.Entities;
using System.Text.Json;

namespace KaPai.Pay.Provide.Dtos
{
    /// <summary>
    /// 输入DTO：收款号列表信息
    /// </summary>
    [MapTo(typeof(ArticleEntities))]
    [Description("收款号列表信息")]
    public partial class ArticleEntitiesInputDto : IInputDto<Guid>
    {
        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public Guid Id { get; set; }

        /// <summary>
        /// 获取或设置 用户ID
        /// </summary>
        [DisplayName("用户ID")]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 类别ID
        /// </summary>
        [DisplayName("类别ID")]
        public Guid ArticleAssortId { get; set; }

        /// <summary>
        /// 获取或设置 名称
        /// </summary>
        [DisplayName("名称"), StringLength(30)]
        public string Name { get; set; }

        /// <summary>
        /// 获取或设置 附加参数
        /// </summary>
        [DisplayName("附加参数")]
        public IDictionary<string,object> Extra { get; set; }

        /// <summary>
        /// 获取或设置 账号备注
        /// </summary>
        [DisplayName("账号备注"), StringLength(200)]
        public string Remarks { get; set; }

        /// <summary>
        /// 获取或设置 状态
        /// </summary>
        [DisplayName("状态")]
        public int Status { get; set; }

    }
}
