// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“PointsLogOutputDto.cs”的分部类“public partial class PointsLogOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="PointsLogOutputDto.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using KaPai.Pay.Provide.Entities;
using KaPai.Pay.Identity.Dtos;

namespace KaPai.Pay.Provide.Dtos
{
    /// <summary>
    /// 输入DTO：积分变动记录信息
    /// </summary>
    [MapFrom(typeof(PointsLog))]
    [Description("积分变动记录信息")]
    public partial class PointsLogOutputDto : IOutputDto, IDataAuthEnabled
    {
        /// <summary>
        /// 初始化一个<see cref="PointsLogOutputDto"/>类型的新实例
        /// </summary>
        public PointsLogOutputDto()
        { }

        /// <summary>
        /// 初始化一个<see cref="PointsLogOutputDto"/>类型的新实例
        /// </summary>
        public PointsLogOutputDto(PointsLog entity)
        {
            Id = entity.Id;
            UserId = entity.UserId;
            PayId = entity.PayId;
            PayType = entity.PayType;
            BeforePoint = entity.BeforePoint;
            AfterPoint = entity.AfterPoint;
            Point = entity.Point;
            Remarks = entity.Remarks;
            CreatedTime = entity.CreatedTime;
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public Guid Id { get; set; }

        /// <summary>
        /// 获取或设置 用户Id
        /// </summary>
        [DisplayName("用户Id")]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 动作Id
        /// </summary>
        [DisplayName("动作Id")]
        public string PayId { get; set; }

        /// <summary>
        /// 获取或设置 影响类型
        /// </summary>
        [DisplayName("影响类型")]
        public string PayType { get; set; }

        /// <summary>
        /// 获取或设置 影响前积分
        /// </summary>
        [DisplayName("影响前积分")]
        public long BeforePoint { get; set; }

        /// <summary>
        /// 获取或设置 影响后积分
        /// </summary>
        [DisplayName("影响后积分")]
        public long AfterPoint { get; set; }

        /// <summary>
        /// 获取或设置 影响积分
        /// </summary>
        [DisplayName("影响积分")]
        public long Point { get; set; }

        /// <summary>
        /// 获取或设置 备注
        /// </summary>
        [DisplayName("备注")]
        public string Remarks { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 是否可更新的数据权限状态
        /// </summary>
        public bool Updatable { get; set; }

        /// <summary>
        /// 获取或设置 是否可删除的数据权限状态
        /// </summary>
        public bool Deletable { get; set; }

    }
}
