// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1. 横向扩展：如需给当前模块添加方法接口，可新建文件“ICashMoneyContract.cs”的分部接口“public partial interface ICashMoneyContract”添加方法，并添加相应新的分部基类 abstract partial class CashMoneyServiceBase 实现新方法
// </auto-generated>
//
//  <copyright file="ICashMoneyContract.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Extensions;

using KaPai.Pay.CashMoney.Dtos;
using KaPai.Pay.CashMoney.Entities;


namespace KaPai.Pay.CashMoney
{
    /// <summary>
    /// 业务契约接口：提现模块模块
    /// </summary>
    public partial interface ICashMoneyContract
    {
        #region 收款账号信息业务

        /// <summary>
        /// 获取 收款账号信息查询数据集
        /// </summary>
        IQueryable<BankList> BankLists { get; }

        /// <summary>
        /// 检查收款账号信息信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的收款账号信息编号</param>
        /// <returns>收款账号信息是否存在</returns>
        Task<bool> CheckBankListExists(Expression<Func<BankList, bool>> predicate, Guid id = default(Guid));
        
        /// <summary>
        /// 添加收款账号信息信息
        /// </summary>
        /// <param name="dtos">要添加的收款账号信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> CreateBankLists(params BankListInputDto[] dtos);
            
        /// <summary>
        /// 更新收款账号信息信息
        /// </summary>
        /// <param name="dtos">包含更新信息的收款账号信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> UpdateBankLists(params BankListInputDto[] dtos);
            
        /// <summary>
        /// 删除收款账号信息信息
        /// </summary>
        /// <param name="ids">要删除的收款账号信息编号</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> DeleteBankLists(params Guid[] ids);
        

        #endregion
        
        #region 提现记录信息业务

        /// <summary>
        /// 获取 提现记录信息查询数据集
        /// </summary>
        IQueryable<CashLog> CashLogs { get; }

        /// <summary>
        /// 检查提现记录信息信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的提现记录信息编号</param>
        /// <returns>提现记录信息是否存在</returns>
        Task<bool> CheckCashLogExists(Expression<Func<CashLog, bool>> predicate, Guid id = default(Guid));
        
        /// <summary>
        /// 添加提现记录信息信息
        /// </summary>
        /// <param name="dtos">要添加的提现记录信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> CreateCashLogs(params CashLogInputDto[] dtos);
        
        #endregion
        
    }
}
