// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“BankListOutputDto.cs”的分部类“public partial class BankListOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="BankListOutputDto.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using KaPai.Pay.CashMoney.Entities;
using KaPai.Pay.Identity.Dtos;

namespace KaPai.Pay.CashMoney.Dtos
{
    /// <summary>
    /// 输入DTO：收款账号信息
    /// </summary>
    [MapFrom(typeof(BankList))]
    [Description("收款账号信息")]
    public partial class BankListOutputDto : IOutputDto, IDataAuthEnabled
    {
        /// <summary>
        /// 初始化一个<see cref="BankListOutputDto"/>类型的新实例
        /// </summary>
        public BankListOutputDto()
        { }

        /// <summary>
        /// 初始化一个<see cref="BankListOutputDto"/>类型的新实例
        /// </summary>
        public BankListOutputDto(BankList entity)
        {
            Id = entity.Id;
            Name = entity.Name;
            Account = entity.Account;
            BankName = entity.BankName;
            BankType = entity.BankType;
            UserId = entity.UserId;
            CreatorId = entity.CreatorId;
            CreatedTime = entity.CreatedTime;
            LastUpdaterId = entity.LastUpdaterId;
            LastUpdatedTime = entity.LastUpdatedTime;
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public Guid Id { get; set; }

        /// <summary>
        /// 获取或设置 开户姓名
        /// </summary>
        [DisplayName("开户姓名")]
        public string Name { get; set; }

        /// <summary>
        /// 获取或设置 银行账号
        /// </summary>
        [DisplayName("银行账号")]
        public string Account { get; set; }

        /// <summary>
        /// 获取或设置 银行名称
        /// </summary>
        [DisplayName("银行名称")]
        public string BankName { get; set; }

        /// <summary>
        /// 获取或设置 开户银行
        /// </summary>
        [DisplayName("开户银行")]
        public string BankType { get; set; }

        /// <summary>
        /// 获取或设置 用户ID
        /// </summary>
        [DisplayName("用户ID")]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 创建者
        /// </summary>
        [DisplayName("创建者")]
        public int? CreatorId { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 更新者
        /// </summary>
        [DisplayName("更新者")]
        public int? LastUpdaterId { get; set; }

        /// <summary>
        /// 获取或设置 更新时间
        /// </summary>
        [DisplayName("更新时间")]
        public DateTime? LastUpdatedTime { get; set; }

        /// <summary>
        /// 获取或设置 是否可更新的数据权限状态
        /// </summary>
        public bool Updatable { get; set; }

        /// <summary>
        /// 获取或设置 是否可删除的数据权限状态
        /// </summary>
        public bool Deletable { get; set; }

    }
}
