// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“CashLogOutputDto.cs”的分部类“public partial class CashLogOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="CashLogOutputDto.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using KaPai.Pay.CashMoney.Entities;
using KaPai.Pay.Identity.Dtos;

namespace KaPai.Pay.CashMoney.Dtos
{
    /// <summary>
    /// 输入DTO：提现记录信息
    /// </summary>
    [MapFrom(typeof(CashLog))]
    [Description("提现记录信息")]
    public partial class CashLogOutputDto : IOutputDto, IDataAuthEnabled
    {
        /// <summary>
        /// 初始化一个<see cref="CashLogOutputDto"/>类型的新实例
        /// </summary>
        public CashLogOutputDto()
        { }

        /// <summary>
        /// 初始化一个<see cref="CashLogOutputDto"/>类型的新实例
        /// </summary>
        public CashLogOutputDto(CashLog entity)
        {
            Id = entity.Id;
            UserId = entity.UserId;
            ProUserId = entity.ProUserId;
            Name = entity.Name;
            BankType = entity.BankType;
            Account = entity.Account;
            BankName = entity.BankName;
            JobId = entity.JobId;
            Remarks = entity.Remarks;
            Status = entity.Status;
            CreatorId = entity.CreatorId;
            CreatedTime = entity.CreatedTime;
            LastUpdaterId = entity.LastUpdaterId;
            LastUpdatedTime = entity.LastUpdatedTime;
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public Guid Id { get; set; }

        /// <summary>
        /// 获取或设置 用户ID
        /// </summary>
        [DisplayName("用户ID")]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 处理用户ID
        /// </summary>
        [DisplayName("处理用户ID")]
        public int? ProUserId { get; set; }

        /// <summary>
        /// 获取或设置 名称
        /// </summary>
        [DisplayName("名称")]
        public string Name { get; set; }

        /// <summary>
        /// 获取或设置 开户银行
        /// </summary>
        [DisplayName("开户银行")]
        public string BankType { get; set; }

        /// <summary>
        /// 获取或设置 收款账号
        /// </summary>
        [DisplayName("收款账号")]
        public string Account { get; set; }

        /// <summary>
        /// 获取或设置 收款银行
        /// </summary>
        [DisplayName("收款银行")]
        public string BankName { get; set; }

        /// <summary>
        /// 获取或设置 任务Id
        /// </summary>
        [DisplayName("任务Id")]
        public string JobId { get; set; }

        /// <summary>
        /// 获取或设置 备注
        /// </summary>
        [DisplayName("备注")]
        public string Remarks { get; set; }

        /// <summary>
        /// 获取或设置 处理状态
        /// </summary>
        [DisplayName("处理状态")]
        public int Status { get; set; }

        /// <summary>
        /// 获取或设置 创建者
        /// </summary>
        [DisplayName("创建者")]
        public int? CreatorId { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 更新者
        /// </summary>
        [DisplayName("更新者")]
        public int? LastUpdaterId { get; set; }

        /// <summary>
        /// 获取或设置 更新时间
        /// </summary>
        [DisplayName("更新时间")]
        public DateTime? LastUpdatedTime { get; set; }

        /// <summary>
        /// 获取或设置 是否可更新的数据权限状态
        /// </summary>
        public bool Updatable { get; set; }

        /// <summary>
        /// 获取或设置 是否可删除的数据权限状态
        /// </summary>
        public bool Deletable { get; set; }

    }
}
