// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“CashLogInputDto.cs”的分部类“public partial class CashLogInputDto”}添加属性
// </auto-generated>
//
//  <copyright file="CashLogInputDto.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using KaPai.Pay.CashMoney.Entities;


namespace KaPai.Pay.CashMoney.Dtos
{
    /// <summary>
    /// 输入DTO：提现记录信息
    /// </summary>
    [MapTo(typeof(CashLog))]
    [Description("提现记录信息")]
    public partial class CashLogInputDto : IInputDto<Guid>
    {
        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public Guid Id { get; set; }

        /// <summary>
        /// 获取或设置 用户ID
        /// </summary>
        [DisplayName("用户ID")]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 处理用户ID
        /// </summary>
        [DisplayName("处理用户ID")]
        public int? ProUserId { get; set; }

        /// <summary>
        /// 获取或设置 名称
        /// </summary>
        [DisplayName("名称"), StringLength(30)]
        public string Name { get; set; }

        /// <summary>
        /// 获取或设置 开户银行
        /// </summary>
        [DisplayName("开户银行"), StringLength(30)]
        public string BankType { get; set; }

        /// <summary>
        /// 获取或设置 收款账号
        /// </summary>
        [DisplayName("收款账号"), StringLength(50)]
        public string Account { get; set; }

        /// <summary>
        /// 获取或设置 收款银行
        /// </summary>
        [DisplayName("收款银行"), StringLength(100)]
        public string BankName { get; set; }

        /// <summary>
        /// 获取或设置 任务Id
        /// </summary>
        [DisplayName("任务Id"), StringLength(50)]
        public string JobId { get; set; }

        /// <summary>
        /// 获取或设置 备注
        /// </summary>
        [DisplayName("备注"), StringLength(100)]
        public string Remarks { get; set; }

        /// <summary>
        /// 获取或设置 处理状态
        /// </summary>
        [DisplayName("处理状态")]
        public int Status { get; set; }

    }
}
