// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前控制器添加API，请在控制器类型 ArticleAssortController.cs 进行添加
//      2.纵向扩展：如需要重写当前控制器的API实现，请在控制器类型 ArticleAssortController.cs 进行继承重写
// </auto-generated>
//
//  <copyright file="ArticleAssortBase.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

using OSharp.AspNetCore.Mvc;
using OSharp.AspNetCore.Mvc.Filters;
using OSharp.AspNetCore.UI;
using OSharp.Caching;
using OSharp.Core.Functions;
using OSharp.Core.Modules;
using OSharp.Data;
using OSharp.Entity;
using OSharp.Filter;
using OSharp.Security;

using KaPai.Pay.Provide;
using KaPai.Pay.Provide.Dtos;
using KaPai.Pay.Provide.Entities;


namespace KaPai.Pay.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// 管理控制器基类: 收款分类列表信息
    /// </summary>
    [ModuleInfo(Position = "Provide", PositionName = "供应商模块")]
    [Description("管理-收款分类列表信息")]
    public abstract class ArticleAssortControllerBase : AdminApiController
    {
        /// <summary>
        /// 初始化一个<see cref="ArticleAssortController"/>类型的新实例
        /// </summary>
        protected ArticleAssortControllerBase(IProvideContract provideContract,
            IFilterService filterService)
        {
            ProvideContract = provideContract;
            FilterService = filterService;
        }

        /// <summary>
        /// 获取或设置 数据过滤服务对象
        /// </summary>
        protected IFilterService FilterService { get; }

        /// <summary>
        /// 获取或设置 供应商模块业务契约对象
        /// </summary>
        protected IProvideContract ProvideContract { get; }
        
        /// <summary>
        /// 读取收款分类列表列表信息
        /// </summary>
        /// <param name="request">页请求信息</param>
        /// <returns>收款分类列表列表分页信息</returns>
        [HttpPost]
        [ModuleInfo]
        [Description("读取")]
        public virtual PageData<ArticleAssortOutputDto> Read(PageRequest request)
        {
            Check.NotNull(request, nameof(request));

            Expression<Func<ArticleAssort, bool>> predicate = FilterService.GetExpression<ArticleAssort>(request.FilterGroup);
            var page = ProvideContract.ArticleAssorts.ToPage<ArticleAssort, ArticleAssortOutputDto>(predicate, request.PageCondition);

            return page.ToPageData();
        }
        
        /// <summary>
        /// 新增收款分类列表信息
        /// </summary>
        /// <param name="dtos">收款分类列表信息输入DTO</param>
        /// <returns>JSON操作结果</returns>
        [HttpPost]
        [ModuleInfo]
        [DependOnFunction("Read")]
        [ServiceFilter(typeof(UnitOfWorkAttribute))]
        [Description("新增")]
        public virtual async Task<AjaxResult> Create(ArticleAssortInputDto[] dtos)
        {
            Check.NotNull(dtos, nameof(dtos));
            OperationResult result = await ProvideContract.CreateArticleAssorts(dtos);
            return result.ToAjaxResult();
        }
        
        /// <summary>
        /// 更新收款分类列表信息
        /// </summary>
        /// <param name="dtos">收款分类列表信息输入DTO</param>
        /// <returns>JSON操作结果</returns>
        [HttpPost]
        [ModuleInfo]
        [DependOnFunction("Read")]
        [ServiceFilter(typeof(UnitOfWorkAttribute))]
        [Description("更新")]
        public virtual async Task<AjaxResult> Update(ArticleAssortInputDto[] dtos)
        {
            Check.NotNull(dtos, nameof(dtos));
            OperationResult result = await ProvideContract.UpdateArticleAssorts(dtos);
            return result.ToAjaxResult();
        }
        
        /// <summary>
        /// 删除收款分类列表信息
        /// </summary>
        /// <param name="ids">收款分类列表信息编号</param>
        /// <returns>JSON操作结果</returns>
        [HttpPost]
        [ModuleInfo]
        [DependOnFunction("Read")]
        [ServiceFilter(typeof(UnitOfWorkAttribute))]
        [Description("删除")]
        public virtual async Task<AjaxResult> Delete(Guid[] ids)
        {
            Check.NotNull(ids, nameof(ids));
            OperationResult result = await ProvideContract.DeleteArticleAssorts(ids);
            return result.ToAjaxResult();
        }
    }
}
