// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前实体 Percentage 添加方法，可新建文件“ChannelServiceBase.Percentage.cs”的分部类“public abstract partial class ChannelServiceBase”添加功能
//      2.纵向扩展：如需要重写当前实体 Percentage 的业务实现，可新建文件“ChannelService.Percentage.cs”的分部类“public partial class ChannelService”对现有方法进行方法重写实现
// </auto-generated>
//
//  <copyright file="ChannelServiceBase.Percentage.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Dependency;
using OSharp.Extensions;
using OSharp.Mapping;

using KaPai.Pay.Channel.Dtos;
using KaPai.Pay.Channel.Entities;
using OSharp.Exceptions;


namespace KaPai.Pay.Channel
{
    public abstract partial class ChannelServiceBase
    {
        /// <summary>
        /// 获取 费率列表信息查询数据集
        /// </summary>
        public IQueryable<Percentage> Percentages
        {
            get { return PercentageRepository.QueryAsNoTracking(); }
        }

        /// <summary>
        /// 检查费率列表信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的费率列表信息编号</param>
        /// <returns>费率列表信息是否存在</returns>
        public virtual Task<bool> CheckPercentageExists(Expression<Func<Percentage, bool>> predicate, Guid id = default(Guid))
        {
            return PercentageRepository.CheckExistsAsync(predicate, id);
        }
        
        /// <summary>
        /// 添加费率列表信息
        /// </summary>
        /// <param name="dtos">要添加的费率列表信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> CreatePercentages(params PercentageInputDto[] dtos)
        {
            Check.Validate<PercentageInputDto, Guid>(dtos, nameof(dtos));
            return PercentageRepository.InsertAsync(dtos, (d) =>
            {
                if (d.Value > 1000)
                {
                    throw new OsharpException("费率值超过最大设置");
                }
                if (d.Value < 0)
                {
                    throw new OsharpException("费率值超过最小设置");
                }
                return Task.CompletedTask;
            });
        }
        
        /// <summary>
        /// 更新费率列表信息
        /// </summary>
        /// <param name="dtos">包含更新信息的费率列表信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> UpdatePercentages(params PercentageInputDto[] dtos)
        {
            Check.Validate<PercentageInputDto, Guid>(dtos, nameof(dtos));
            return PercentageRepository.UpdateAsync(dtos, (d, p) =>
            {
                if (d.Value > 1000)
                {
                    throw new OsharpException("费率值超过最大设置");
                }
                if (d.Value < 0)
                {
                    throw new OsharpException("费率值超过最小设置");
                }
                return Task.CompletedTask;

            });
        }
    }
}
