//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“BankList.cs”的分部类“public partial class BankList”}添加属性
// </auto-generated>
//
//  <copyright file="BankList.generated.cs">
//      KaPai©2019 Microsoft Corporation. All rights reserved. 
//  </copyright>
//  <site></site>
//  <last-editor>KaPai</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;

using KaPai.Pay.Identity.Entities;

namespace KaPai.Pay.CashMoney.Entities
{
    /// <summary>
    /// 实体类：收款账号信息
    /// </summary>
    [Description("收款账号信息")]
    public partial class BankList : EntityBase<Guid>, ICreationAudited<int>, IUpdateAudited<int>
    {
        /// <summary>
        /// 获取或设置 开户姓名
        /// </summary>
        [DisplayName("开户姓名"), Required, StringLength(20)]
        public string Name { get; set; }

        /// <summary>
        /// 获取或设置 银行账号
        /// </summary>
        [DisplayName("银行账号"), Required, StringLength(100)]
        public string Account { get; set; }

        /// <summary>
        /// 获取或设置 银行名称
        /// </summary>
        [DisplayName("银行名称"), Required, StringLength(100)]
        public string BankName { get; set; }

        /// <summary>
        /// 获取或设置 开户银行
        /// </summary>
        [DisplayName("开户银行"), StringLength(100)]
        public string BankType { get; set; }

        /// <summary>
        /// 获取或设置 创建者
        /// </summary>
        [DisplayName("创建者")]
        public int? CreatorId { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 更新者
        /// </summary>
        [DisplayName("更新者")]
        public int? LastUpdaterId { get; set; }

        /// <summary>
        /// 获取或设置 更新时间
        /// </summary>
        [DisplayName("更新时间")]
        public DateTime? LastUpdatedTime { get; set; }

        /// <summary>
        /// 获取或设置 用户ID
        /// </summary>
        [DisplayName("用户ID"), UserFlag]
        public int UserId { get; set; }

        /// <summary>
        /// 获取或设置 所属用户
        /// </summary>
        [DisplayName("所属用户")]
        public virtual User User { get; set; }

    }
}

